/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AttemptSchema extends BaseModel {
  static $columns = ['createdAt', 'feedback', 'id', 'questionId', 'response', 'score'] as const
  $columns = AttemptSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare feedback: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare questionId: string
  @column()
  declare response: string
  @column()
  declare score: number
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OauthAuthorizationCodeSchema extends BaseModel {
  static $columns = [
    'clientId',
    'codeChallenge',
    'codeChallengeMethod',
    'codeHash',
    'createdAt',
    'expiresAt',
    'id',
    'redirectUri',
    'resource',
    'scopes',
    'userId',
  ] as const
  $columns = OauthAuthorizationCodeSchema.$columns
  @column()
  declare clientId: string
  @column()
  declare codeChallenge: string
  @column()
  declare codeChallengeMethod: string
  @column()
  declare codeHash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare redirectUri: string
  @column()
  declare resource: string
  @column()
  declare scopes: any
  @column()
  declare userId: number
}

export class QuestionSchema extends BaseModel {
  static $columns = [
    'answer',
    'context',
    'createdAt',
    'id',
    'prompt',
    'rubricId',
    'skillId',
  ] as const
  $columns = QuestionSchema.$columns
  @column()
  declare answer: string | null
  @column()
  declare context: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare prompt: string
  @column()
  declare rubricId: string
  @column()
  declare skillId: string
}

export class RubricSchema extends BaseModel {
  static $columns = ['data', 'description', 'id', 'maxScore', 'name', 'type'] as const
  $columns = RubricSchema.$columns
  @column()
  declare data: any
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare maxScore: number
  @column()
  declare name: string
  @column()
  declare type: string
}

export class SkillSchema extends BaseModel {
  static $columns = ['description', 'id', 'name', 'parentId'] as const
  $columns = SkillSchema.$columns
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare parentId: string | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'firstName',
    'id',
    'lastName',
    'password',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare firstName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastName: string | null
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
